version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: laminas/laminas-code
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
  - dependency-name: symfony/maker-bundle
    versions:
    - 1.30.0
    - 1.30.1
  - dependency-name: sensio/framework-extra-bundle
    versions:
    - 6.1.1
  - dependency-name: symfony/translation
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/asset
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/expression-language
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/console
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/flex
    versions:
    - 1.11.0
    - 1.12.1
    - 1.12.2
  - dependency-name: symfony/web-link
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/security-bundle
    versions:
    - 5.1.11
  - dependency-name: symfony/http-kernel
    versions:
    - 5.1.11
  - dependency-name: symfony/framework-bundle
    versions:
    - 5.1.10
  - dependency-name: symfony/http-client
    versions:
    - 5.1.5
